config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  # Static Page Route
  get '/pages/help-and-faq' => 'pages#help_and_faq'
  get '/pages/contact-us' => 'pages#contact_us'

 # CRUD
  resources :categories do
    resources :subcategories
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :category
  belongs_to :subcategory
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @community_category = Category.find_by(:name => "Community")
    @personal_category  = Category.find_by(:name => "Personals")
    @housing_category   = Category.find_by(:name => "Housing")
    @for_sale_category  = Category.find_by(:name => "Sale")
    @service_category   = Category.find_by(:name => "Services")
    @jobs_category      = Category.find_by(:name => "Jobs")
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def help_and_faq

  end

  def contact_us

  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController

  def show
    @subcategory = Subcategory.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="container">
    <div class="leftbar">
        <a href="#"><h1 class="app-title">Railings</h1></a>
        <ul>
            <a href="#">Post</a>
            <li>Account</li>
        </ul>
        <form>
            <p>Search</p>
            <input type="text" name="firstname" placeholder="search" size="20">
            <br>
            <input type="text" name="firstname" placeholder="where" size="20">
            <br>
            <select>
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="mercedes">Mercedes</option>
                <option value="audi">Audi</option>
            </select>
            <button type="button">>
            </button>
        </form>
    </div>
    <div class="center-column" >
        <div class="center-one">
            <table>
                <tr>
                    <th class="table-header">
                        <%= link_to @community_category.name, category_path(@community_category)%>
                    </th>
                </tr>
                <tr>
                    <td>
                        <ul>
                            <% @community_category.subcategories.each do |subcategory|%>
                            <li>
                                <%= link_to subcategory.name, category_subcategory_path(@community_category, subcategory)%>
                            </li>
                            <% end %>
                        </ul>
                    </td>
                </tr>
            </table>
            <table>
                <tr>
                    <th class="table-header">
                        <%= @personal_category.name %>
                    </th>
                </tr>
                <tr>
                    <td>
                        <ul>
                            <% @personal_category.subcategories.each do |subcategory|%>
                            <li>
                                <%= subcategory.name%>
                            </li>
                            <% end %>
                        </ul>
                    </td>
                </tr>
            </table>
            <table>
                <tr>
                    <th class="table-header">
                        <%= @service_category.name %>
                    </th>
                </tr>
                <tr>
                    <td>
                        <ul class="left-list">
                            <% @service_category.subcategories.each do |subcategory|%>
                            <li>
                                <%= subcategory.name %>
                            </li>
                            <% end %>
                        </ul>
                    </td>
                </tr>
            </table>
        </div>
        <div class="center-two">
            <table>
                <tr>
                    <th class="table-header">
                    <%= @housing_category.name %>
                    </th>
                </tr>
                <tr>
                    <td>
                        <ul >
                            <% @housing_category.subcategories.each do |subcategory|%>
                                <li>
                                    <%= subcategory.name %>
                                </li>
                            <% end %>
                        </ul>
                    </td>
                </tr>
            </table>
            <table>
                <tr>
                    <th class="table-header">
                        <%= @for_sale_category.name %>
                    </th>
                </tr>
                <tr>
                    <td>
                        <ul>
                        <% @for_sale_category.subcategories.each do |subcategory|%>
                            <li>
                                <%= subcategory.name %>
                            </li>
                        <% end %>
                        </ul>
                    </td>
                </tr>
            </table>
        </div>
        <div class="center-three">
            <table>
                <tr>
                    <th class="table-header">
                        <%= @jobs_category.name %>
                    </th>
                </tr>
                <tr>
                    <td>
                        <ul>
                            <% @jobs_category.subcategories.each do |subcategory|%>
                                <li>
                                    <%= subcategory.name %>
                                </li>
                            <% end %>
                        </ul>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="rightbar">
        <ul class="rightbar-top">
            <li><%= link_to 'Help and FAQ', pages_help_and_faq_path %></li>
            <li>avoid scams & fraud</li>
            <li>personal safety tips</li>
            <li class="rightbar-top">terms of use</li>
            <li>privacy policy</li>
            <li>about rubyslist</li>
            <li><%= link_to 'Contact Us', pages_contact_us_path %></li>
        </ul>
    </div>
</div>

app/views/categories/show.html.erb
<div class="topbar">
    <div class="container">
        <div class="vertical-center">
            <%= link_to "Railings", root_path %> >
            <%= link_to @category.name, category_path(@category)%>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="newest">newest</div>
        <div class="oldest">oldest</div>
        <div class="highest-price">highest-price</div>
        <div class="lowest-price">lowest-price</div>
    </div>
    <ul class="list-margin">
        <li><span>November 14</span> Listing here! (MN)</li>
        <li><span>November 14</span> Listing here! (MN)</li>
        <li><span>November 14</span> Listing here! (MN)</li>
        <li><span>November 14</span> Listing here! (MN)</li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railings</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/contact_us.html.erb
<h1>You cant just contact us !</h1>

app/views/pages/help_and_faq.html.erb
<h1>Help and FAQ</h1>

app/views/subcategories/show.html.erb
<div class="topbar">
    <div class="container">
        <div class="vertical-center">
            <%= link_to "Railings", root_path %> >
            <%= link_to @subcategory.category.name, category_path(@subcategory.category_id)%> >
            <%= link_to @subcategory.name, category_path(@subcategory.category_id)%>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="newest">newest</div>
        <div class="oldest">oldest</div>
        <div class="highest-price">highest-price</div>
        <div class="lowest-price">lowest-price</div>
    </div>
    <ul class="list-margin">
        <li><span>November 14</span> Listing here! (MN)</li>
        <li><span>November 14</span> Listing here! (MN)</li>
        <li><span>November 14</span> Listing here! (MN)</li>
        <li><span>November 14</span> Listing here! (MN)</li>
    </ul>
</div>